openapi3.yaml, src/DAL/entity/partialTask.ts, src/DAL/repositories/partialTaskRepository.ts, src/common/interfaces.ts
| Breaking change | ✔                                                                        | …
=> refactor(discrete task): rename discrete task entity column retries to attempts

openapi3.yaml, src/DAL/entity/partialTask.ts, src/DAL/repositories/partialTaskRepository.ts, src/common/interfaces.ts, src/common/utils/convertTaskStatusesToResponse.ts, src/partialTask/controllers/partialTaskController.ts, src/partialTask/models/partialTaskManager.ts, src/partialTask/routes/partialTaskRouter.ts, tests/unit/partialTask/helpers/data.ts, tests/unit/partialTask/partialTask.spec.ts
| Tests added     | ✔                                                                        | …
=> chore(route): add route for getting summary of partial task statuses by discrete

src/DAL/repositories/discreteTaskRepository.ts, src/DAL/repositories/partialTaskRepository.ts, src/common/errors.ts, src/discreteTask/controllers/discreteTaskController.ts, src/discreteTask/models/discreteTaskManager.ts, src/partialTask/controllers/partialTaskController.ts, src/partialTask/models/partialTaskManager.ts, tests/integration/discreteTask/discreteTask.spec.ts, tests/integration/discreteTask/helpers/data.ts, tests/integration/partialTask/partialTask.spec.ts, tests/unit/discreteTask/discreteTask.spec.ts, tests/unit/partialTask/partialTask.spec.ts
=> Custom errors

.eslintrc.json, .prettierignore, CHANGELOG.md, package-lock.json, package.json, src/DAL/migration/1615284669708-migration-V1_0_1.ts
| Bug fix         |✖                                                                        |
| Chore            | ✔ …
=> chore: migration

src/DAL/entity/job.ts
| Bug fix         | ✔/                                                                      |
| New feature     | ✔✖                                                                        | …
=> fix: fixed index nameing

.github/workflows/release-on-tag-push.yaml
=> chore: added release on tag

src/DAL/entity/job.ts, src/DAL/entity/task.ts, src/DAL/migration/FullSchema.sql, src/DAL/migration/v2.1.0.sql
| Bug fix         | ✔                                                                     |
| New feature     |  ✖                                                                        |
| Chore            | ✖ …
=> fix: added timezone to db timestamps

config/custom-environment-variables.json, package-lock.json, package.json
=> feat: fix audit and ssl config format

.gitignore
| Chore            | ✔                                                                       |
Related issues: #XXX , #XXX ...
Closes #XXX ...
Further  information:
=> chore: add idea folder to git ignore

src/taskManagement/controllers/taskManagementController.ts, src/taskManagement/models/taskManagementManger.ts
| Bug fix         | ✔/                                                                       |
=> fix: don't print error message on no pending task response

openapi3.yaml, src/DAL/repositories/jobRepository.ts, src/common/dataModels/jobs.ts, src/jobs/controllers/jobController.ts, src/jobs/models/jobManager.ts, tests/integration/jobs/helpers/jobsRequestSender.ts, tests/integration/jobs/jobs.spec.ts
| New feature     | ✔                                                                       |
=> feat: Jobs with no tasks

openapi3.yaml, package-lock.json, src/DAL/convertors/taskModelConvertor.ts, src/DAL/repositories/taskRepository.ts, src/common/dataModels/tasks.ts, src/jobs/controllers/jobController.ts, src/jobs/controllers/taskController.ts, src/jobs/models/taskManager.ts, src/jobs/routes/jobRouter.ts, src/taskManagement/controllers/taskManagementController.ts, src/taskManagement/routes/taskManagerRouter.ts, tests/integration/jobs/helpers/tasksRequestSender.ts, tests/integration/jobs/tasks.spec.ts
=> feat: full find tasks implementation

src/DAL/connectionManager.ts
=> fix: connection creation duplucation

openapi3.yaml, src/DAL/entity/job.ts, src/DAL/migration/FullSchema.sql, src/DAL/migration/v2.3.0.sql, src/DAL/repositories/jobRepository.ts, src/DAL/repositories/taskRepository.ts, src/common/dataModels/enums.ts, src/common/dataModels/tasks.ts, src/taskManagement/controllers/taskManagementController.ts, src/taskManagement/models/taskManagementManger.ts, src/taskManagement/routes/taskManagerRouter.ts, tests/__mocks__/typeorm.ts, tests/integration/taskManagement/helpers/taskManagementRequestSender.ts, tests/integration/taskManagement/taskManagement.spec.ts, tests/mocks/DBMock.ts, tests/testContainerConfig.ts, tests/unit/DAL/jobModelConverter.spec.ts, tests/unit/DAL/taskModelConverter.spec.ts
| Tests added     | ✔                                                                        | …
=> feat: exparation and inactive tasks black list

openapi3.yaml, src/DAL/connectionManager.ts, src/DAL/entity/task.ts, src/DAL/migration/FullSchema.sql, src/DAL/migration/v2.4.sql, src/DAL/repositories/jobRepository.ts, src/DAL/repositories/taskRepository.ts, src/DAL/repositories/transactionActions.ts, src/common/dataModels/jobs.ts, src/common/errors.ts, src/jobs/controllers/jobController.ts, src/jobs/models/jobManager.ts, src/jobs/routes/jobRouter.ts, tests/__mocks__/typeorm.ts, tests/integration/jobs/helpers/jobsRequestSender.ts, tests/integration/jobs/jobs.spec.ts, tests/mocks/DBMock.ts
| Documentation   | ✔                                                                        |
| Tests added     | ✔                                                                        | …
=> feat: job reset

.gitignore, openapi3.yaml
=> feat!: set 'type' as a mandatory field when creating a task

config/custom-environment-variables.json, config/default.json, config/test.json, helm/templates/configmap.yaml, helm/values.yaml, src/serverBuilder.ts
=> feat: add payload limit config

config/custom-environment-variables.json, config/default.json, config/test.json
=> fix: payload limit config location

src/DAL/repositories/taskRepository.ts
=> chore: fix spelling

openapi3.yaml, src/DAL/entity/job.ts, src/DAL/migration/FullSchema.sql, src/DAL/migration/v3.1.0.sql, src/common/dataModels/jobs.ts, tests/unit/DAL/jobModelConverter.spec.ts
| Documentation   | ✔                                                                        | …
=> feat: added task counters

helm/templates/configmap.yaml
=> fix: port quote

.gitignore, helm/templates/_helpers.tpl, helm/templates/configmap.yaml, helm/templates/deployment.yaml, helm/templates/postgres-secrect.yaml, helm/values.yaml
=> chore: common config support

openapi3.yaml, src/DAL/entity/job.ts, src/DAL/migration/FullSchema.sql, src/DAL/migration/v3.1.3.sql, src/common/dataModels/jobs.ts, tests/unit/DAL/jobModelConverter.spec.ts
=> feat: add Job constarint

openapi3.yaml, src/DAL/repositories/transactionActions.ts, src/common/dataModels/jobs.ts, src/jobs/controllers/jobController.ts, src/jobs/models/jobManager.ts, tests/integration/jobs/helpers/jobsRequestSender.ts, tests/integration/jobs/jobs.spec.ts
=> feat: add new expiration date to reset route

.licrc, helm/templates/ca-secret.yaml, helm/templates/deployment.yaml, helm/templates/ssl-secret.yaml, helm/values.yaml
=> chore: add ca and ssl insertion

helm/templates/configmap.yaml, helm/templates/deployment.yaml
=> fix: ssl locations

helm/values.yaml
=> chore: fix defult values

helm/templates/deployment.yaml, helm/values.yaml
=> chore: pods auto restart

openapi3.yaml, src/common/dataModels/jobs.ts
=> chore: added product type as query parameter

openapi3.yaml, src/DAL/repositories/jobRepository.ts, src/common/dataModels/jobs.ts, tests/__mocks__/typeorm.ts, tests/configurations/integration/jest.config.js, tests/configurations/unit/jest.config.js, tests/integration/jobs/helpers/jobsRequestSender.ts, tests/integration/jobs/jobs.spec.ts, tests/mocks/DBMock.ts
=> Find job update date filters

src/common/middlewares/urlQueryDecoder.ts, src/serverBuilder.ts, tests/integration/jobs/jobs.spec.ts
=> fix: encoded query params support

openapi3.yaml, src/common/dataModels/tasks.ts, tests/unit/DAL/jobModelConverter.spec.ts, tests/unit/DAL/taskModelConverter.spec.ts
=> chore: fix openAPI and tests (add resettable field criteriad to task response)

src/DAL/entity/job.ts, src/DAL/entity/task.ts, tests/integration/jobs/tasks.spec.ts, tests/integration/taskManagement/taskManagement.spec.ts, tests/unit/DAL/taskModelConverter.spec.ts
=> fix: fix tasks API to return jobId field

package-lock.json, package.json, src/index.ts, tests/integration/jobs/jobs.spec.ts
=> fix: remove unused mc-models-types deps

.github/workflows/build_and_push.yaml
=> ci: update secret value to azure

openapi3.yaml, src/DAL/entity/task.ts, src/DAL/migration/FullSchema.sql, src/DAL/migration/v4.0.0.sql, src/DAL/repositories/jobRepository.ts, src/DAL/repositories/taskRepository.ts, src/common/dataModels/tasks.ts, tests/integration/jobs/jobs.spec.ts, tests/integration/jobs/tasks.spec.ts
=> feat: Block task duplication
